version: "3.7"
services:
  app:
    build:
      args:
        user: aceplus
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: foodiepanzel-api
    container_name: foodiepanzel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: recipe_project-db
    restart: unless-stopped
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: foodiepanzel-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - backend
volumes:
  mysqldb:

networks:
  backend:
    name: backend
    external: true
